config/routes.rb
Carshare::Application.routes.draw do
  get "home/index"

  devise_for :users

  if Rails.env.development?
    match "debug" => "debug#index"
    get "debug/index"
    get "debug/jquery_ui_test"
    get "debug/geocoder"
  end

  root :to => 'home#index'

end

app/models/city.rb
# == Schema Information
#
# Table name: cities
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  lat        :float
#  lon        :float
#  created_at :datetime
#
# Indexes
#
#  index_cities_on_name  (name) UNIQUE
#

class City < ActiveRecord::Base
end

# vim: ts=2 sw=2

app/models/user.rb
require 'devise'

class User
  include Mongoid::Document

  field :username
  key :username

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

# vim: ts=2 sw=2

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

# vim: ts=2 sw=2

app/controllers/debug_controller.rb
require 'geocoder'

class DebugController < ApplicationController
    def index
    end

    def jquery_ui_test
    end

    def geocoder
        if params[:q].nil?
            @text = ""
        else
            @text = Geocoder.search(params[:q])
        end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

# vim: ts=2 sw=2

app/helpers/application_helper.rb
module ApplicationHelper
end

# vim: ts=2 sw=2

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

# vim: ts=2 sw=2

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

# vim: ts=2 sw=2

app/views/debug/geocoder.html.erb
<% title "Geocoder" %>
<%= form_tag nil, :method => :get do %>
    <%= text_field_tag :q %><br/>
    <%= submit_tag "Submit" %>
<% end %>
<%= @text %>

app/views/debug/index.html.erb
<% title 'Debug stuff' %>
<ul>
    <li><%= link_to "Some jquery-ui tests", debug_jquery_ui_test_path %>
    <li><%= link_to "Geocoder", debug_geocoder_path %>
</ul>

app/views/debug/jquery_ui_test.html.erb
<% title "jquery-ui test" %>

<script>
    $(function() {
        $( "#autocomplete" ).autocomplete({source: ['123', '234', '345']});
        $( "#datepicker" ).datepicker($.datepicker.regional['ru']);
        $( "#datepicker" ).datepicker('option', $.datepicker.regional['ru']);
    });
</script>

<div class="demo">
    <label for="autocomplete">Autocomplete (123, 234, 345): </label>
    <input id="autocomplete"><br />

    <label for="datepicker">Date: </label>
    <input id="datepicker">
</div><!-- End demo -->

app/views/home/_search.html.erb
<%= form_tag("/search", :method => "get") do %>
  <%= label_tag :q1, "Yandex:" %>
  <%= text_field_tag :q1, nil, :geocomplete => :yandex, :style => "width: 1000px" %> <br />

  <%= label_tag :q2, "Google:" %>
  <%= text_field_tag :q2, nil, :geocomplete => :google, :style => "width: 1000px" %> <br />

  <%= submit_tag "Search" %>
<% end %>

<!-- vim: set ts=2 sw=2: -->

app/views/home/index.html.erb
<% title "Home" %>
<%= render 'search' %>

<!-- vim: set ts=2 sw=2: -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Carshare" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "http://maps.googleapis.com/maps/api/js?libraries=places&sensor=false&language=ru" %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <%= render "shared/nav_header" %>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

<!-- vim: set ts=2 sw=2: -->

app/views/shared/_nav_header.html.erb
<div id="nav_header">
  <div class="left">
    <%= link_to "Home", root_path %>
    <% if Rails.env.development? %>
      <%= link_to "Debug", debug_path %>
    <% end %>
  </div>
  <div class="right">
    <% if user_signed_in? %>
      <b><%= current_user.email %></b>
      <%= link_to "Log out", destroy_user_session_path, :method => :delete %><br />
    <% else %>
      <%= link_to "Sign in", new_user_session_path %>
      <%= link_to "Sign up", new_user_registration_path %><br />
    <% end %>
  </div>
</div>

<!-- vim: set ts=2 sw=2: -->

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>